name: Keep Render Alive

on:
  schedule:
    - cron: "*/15 * * * *"   # каждые 20 минут
  workflow_dispatch:         # запуск руками при надобности

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render service
        run: curl -fsS https://<твоя-ссылка-на-render>.onrender.com/health > /dev/null
