name: Keep Render Alive

on:
  schedule:
    - cron: "*/20 * * * *"   # каждые 20 минут
  workflow_dispatch:        # можно запустить вручную

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /health
        run: curl -fsS -o /dev/null https://akvarel-rhythmic-form.onrender.com/health
